# permissions for end users to edit autoscaleconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autoscaleconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-autoscaler
    app.kubernetes.io/part-of: pvc-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: autoscaleconfig-editor-role
rules:
- apiGroups:
  - autoscaler.percona.com
  resources:
  - autoscaleconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.percona.com
  resources:
  - autoscaleconfigs/status
  verbs:
  - get
